/**
 * Shape of the bundled container loot tables (src/main/data/containerLoot.json), generated by
 * scripts/build-container-loot.ts from SPT's per-map staticLoot.json files.
 */
export interface ContainerLootData {
  source: string
  sourceUrl: string
  license: string
  /** ISO date the file was generated. */
  generatedAt: string
  /** Month of the newest item in the tables (YYYY-MM): roughly how current the data is. */
  dataAsOf: string
  maps: { id: string; name: string }[]
  /** Item ids, referenced by index from `loot` to keep the file small. */
  items: string[]
  containers: ContainerLootEntry[]
}

export interface ContainerLootEntry {
  /** Slug of the container name; variants sharing a name are merged. */
  id: string
  name: string
  /** The game's template ids merged into it (how tarkov.dev's maps name the container at each spot). */
  templates?: string[]
  maps: Record<string, ContainerMapLoot>
}

export interface ContainerMapLoot {
  /** How many times the container's item count was observed (weights the cross-map average). */
  observations: number
  /** Average number of items one search rolls. */
  expectedCount: number
  /** Flat [itemIndex, weight, itemIndex, weight, …]; weights are relative observation counts. */
  loot: number[]
}
